# Generated by Django 4.1.5 on 2023-01-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imageuploder',
            new_name='uploder',
        ),
    ]
