# Generated by Django 4.1.5 on 2023-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_categories_category_uploder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploder',
            name='decription',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
