# Generated by Django 4.1.5 on 2023-01-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploder_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
    ]
