# Generated by Django 4.1.5 on 2023-01-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_uploder_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
