# Generated by Django 4.1.5 on 2023-01-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploder',
            old_name='decription',
            new_name='discription',
        ),
    ]
